import Main from '@/components/Main'
import Head from 'next/head'
import Image from 'next/image'
import About from '@/pages/about'
import Skills from '@/pages/skills'
import Contact from '@/pages/contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Charlie | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  )
}
